# Generated by Django 4.2.1 on 2024-07-31 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], max_length=100, null=True)),
                ('begin_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('duration_cycle', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=100, null=True)),
                ('auto_extended', models.BooleanField(default=False)),
                ('extend_duration', models.IntegerField(blank=True, null=True)),
                ('extend_cycle', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=100, null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_terminated', models.BooleanField(default=False, null=True)),
                ('termination_duration', models.IntegerField(null=True)),
                ('termination_cycle', models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=100, null=True)),
                ('termination_date', models.DateField(null=True)),
                ('terminated_on', models.DateField(null=True)),
                ('approval_status', models.CharField(choices=[('draft', 'DRAFT'), ('review', 'REVIEW'), ('published', 'PUBLISHED')], default='draft', max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_status_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractApprovals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.CharField(blank=True, choices=[('approve', 'APPROVE'), ('reject', 'REJECT')], max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contract approvals',
            },
        ),
        migrations.CreateModel(
            name='ContractCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contract categories',
            },
        ),
        migrations.CreateModel(
            name='ContractFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(null=True, upload_to='files/contractfiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contract logs',
            },
        ),
        migrations.CreateModel(
            name='ContractSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, null=True, unique=True)),
                ('contract_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractcategory')),
            ],
            options={
                'verbose_name_plural': 'Contract sub categories',
            },
        ),
        migrations.CreateModel(
            name='ContractPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('contract_id', models.ManyToManyField(related_name='contract_id', to='contracts.contract')),
            ],
        ),
    ]
