# Generated by Django 4.2.1 on 2024-07-31 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpartner',
            name='partner_id',
            field=models.ManyToManyField(to='partners.partner'),
        ),
        migrations.AddField(
            model_name='contractlogs',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractlogs',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractframework',
            name='contract_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractframework',
            name='individual_contract_id',
            field=models.ManyToManyField(related_name='induvidual_contract', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractfile',
            name='contract_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractapprovals',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractapprovals',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='contractapprovals',
            name='partner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='contractapprovals',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contractcategory'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='contract',
            name='made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_by', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='contract',
            name='made_by_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_by_type', to='partners.type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='made_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_to', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='contract',
            name='made_to_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_to_type', to='partners.type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sub_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contractsubcategory'),
        ),
    ]
