# Generated by Django 4.2.1 on 2024-07-31 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('projectmanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklistitems',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklistitems',
            name='checklistitems_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.checklistitems'),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklistitems',
            name='tasktemplatechecklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.tasktemplatechecklist'),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklist',
            name='checklist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.checklist'),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklist',
            name='checklist_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.checklistitems'),
        ),
        migrations.AddField(
            model_name='tasktemplatechecklist',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectphasetasktemplate'),
        ),
        migrations.AddField(
            model_name='taskchecklistitems',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskchecklistitems',
            name='checklistitems_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.checklistitems'),
        ),
        migrations.AddField(
            model_name='taskchecklistitems',
            name='taskchecklist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.taskchecklist'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='checklist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterdata.checklist'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='checklist_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.checklistitems'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectphasetask'),
        ),
        migrations.AddField(
            model_name='tabfields',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.field'),
        ),
        migrations.AddField(
            model_name='tabfields',
            name='tab_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.tab'),
        ),
        migrations.AddField(
            model_name='projectphasetaskfields',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.field'),
        ),
        migrations.AddField(
            model_name='projectphasetaskfields',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.projectphasetask'),
        ),
        migrations.AddField(
            model_name='locationfields',
            name='field_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.field'),
        ),
        migrations.AddField(
            model_name='locationfields',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationfields',
            name='tab_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.tab'),
        ),
        migrations.AddField(
            model_name='groupview',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.group'),
        ),
        migrations.AddField(
            model_name='groupview',
            name='group_module_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_module', to='masterdata.groupmodule'),
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterdata.field'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_fields', to='masterdata.group'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='group_module_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.groupmodule'),
        ),
        migrations.AddField(
            model_name='checklistitems',
            name='checklist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.checklist'),
        ),
    ]
