from masterdata.models import Field


fields = [
   {'id': 1, 'name': 'Project name',                     'field_type':'text',    'display_order':1},
   {'id': 2, 'name': 'Project-No.',                      'field_type':'text',    'display_order':2},
   {'id': 3, 'name': 'City',                             'field_type':'text',    'display_order':3},
   {'id': 4, 'name': 'Zip Code',                         'field_type':'integer',     'display_order':4},
   {'id': 5, 'name': 'Street',                           'field_type':'text',    'display_order':5},
   {'id': 6, 'name': 'Landowner',                        'field_type':'dependecy',    'display_order':6},
   {'id': 7, 'name': 'Asset-ID',                         'field_type':'dependency',    'display_order':7},
   {'id': 8, 'name': 'Asset-Manager',                    'field_type':'dependency',    'display_order':8},
   {'id': 9, 'name': 'Anchor Tenant',                    'field_type':'dependency',    'display_order':9},
   {'id': 10, 'name': 'Tenant Structure',                'field_type':'dropdown', 'options':['MT', 'ST'], 'display_order':10},
   {'id': 11, 'name': 'Grid Operator',                   'field_type':'dependency',    'display_order':11},
   {'id': 12, 'name': 'Scope',                           'field_type':'text',    'display_order':12},
   {'id': 13, 'name': 'Expected kWp PV',                 'field_type':'decimal',    'display_order':13},
   {'id': 14, 'name': 'Expected Spec Yield(kWh/kWp)',    'field_type':'decimal', 'display_order':14},
   {'id': 15, 'name': 'Expected Installation Date PV',   'field_type':'date', 'display_order':15},
   {'id': 16, 'name': 'Planned Installation Date PV',   'field_type':'date',    'display_order':16},
   {'id': 17, 'name': 'Expected oper. Date PV',           'field_type':'date',    'display_order':17},
   {'id': 18, 'name': 'Offtakers PV',                    'field_type':'text',    'display_order':18},
   {'id': 19, 'name': 'Lead Manger PV',                  'field_type':'dependency',    'display_order':19},
   {'id': 20, 'name': 'Snow Load Factor',                'field_type':'text',    'display_order':20},
   {'id': 21, 'name': 'Prioritization',                  'field_type':'text', 'display_order':21}
   
]

# fields = [
#    {'id': 1, 'name': 'Status EV',  'field_type':'dropdown', 'options':['0 - Early-Stage', '1 - Lead', '2 - Pitch', '3 - Negotiations', '4 - LOI Signed/Development', '5 - Construction Ready', '6 - Construction', '7 - Installed', '8 - Operating', '9 - Discontinued', 'H - On Hold'], 'display_order':63},
#    {'id': 2, 'name': 'Parking Spots', 'field_type':'integer', 'display_order':2},
#    {'id': 3, 'name': 'Approval EV', 'field_type':'text', 'display_order':3},
#    {'id': 4, 'name': 'Milestone Date', 'field_type':'date', 'display_order':4},
#    {'id': 5, 'name': 'Disc Reason EV', 'field_type':'text', 'display_order':5},
#    {'id': 6, 'name': 'Planned AC', 'field_type':'decimal', 'display_order':6},
#    {'id': 7, 'name': 'AC Speed', 'field_type':'decimal', 'display_order':7},
#    {'id': 8, 'name': 'AC Tech Setup', 'field_type':'text', 'display_order':8},
#    {'id': 9, 'name': 'Planned DC', 'field_type':'decimal', 'display_order':9},
#    {'id': 10, 'name': 'DC Speed', 'field_type':'decimal', 'display_order':10},
#    {'id': 11, 'name': 'DC Tech Setup', 'field_type':'text', 'display_order':11},
#    {'id': 12, 'name': 'Planned Battery', 'field_type':'decimal', 'display_order':12},
#    {'id': 13, 'name': 'Battery Speed', 'field_type':'decimal', 'display_order':13},
#    {'id': 14, 'name': 'Battery Tech Setup', 'field_type':'text', 'display_order':14},
#    {'id': 15, 'name': 'Construction Year', 'field_type':'integer', 'display_order':15},
#    {'id': 16, 'name': 'Construction Quarter', 'field_type':'text', 'display_order':16},
#    {'id': 17, 'name': 'Exp Installation Date', 'field_type':'date', 'display_order':17},
#    {'id': 18, 'name': 'Planned Installation Date', 'field_type':'date', 'display_order':18},
#    {'id': 19, 'name': 'Exp Operation Date', 'field_type':'date', 'display_order':19},
#    {'id': 20, 'name': 'GEAP EV', 'field_type':'text', 'display_order':20},
#    {'id': 21, 'name': 'GEP EV', 'field_type':'decimal', 'display_order':21},
#    {'id': 22, 'name': 'Capex Spent To Date', 'field_type':'date', 'display_order':22},
#    {'id': 23, 'name': 'Capex Total Expected', 'field_type':'decimal', 'display_order':23},
#    {'id': 24, 'name': 'Subsidy', 'field_type':'text', 'display_order':24},
#    {'id': 25, 'name': 'Asset Management Comments', 'field_type':'longtext', 'display_order':25},
#    {'id': 26, 'name': 'Apprvoal CS', 'field_type':'longtext', 'display_order':26},
#    {'id': 27, 'name': 'Pitch EV', 'field_type':'text', 'display_order':27},
#    {'id': 28, 'name': 'Negotiations EV', 'field_type':'text', 'display_order':28},
#    {'id': 29, 'name': 'LOI', 'field_type':'text', 'display_order':29},
#    {'id': 30, 'name': 'Setup EV', 'field_type':'text', 'display_order':30},
#    {'id': 31, 'name': 'Construction EV', 'field_type':'text', 'display_order':31},
#    {'id': 32, 'name': 'Installed EV', 'field_type':'text', 'display_order':32},
#    {'id': 33, 'name': 'Operating EV', 'field_type':'text', 'display_order':33},
#    {'id': 34, 'name': 'Invoice Number EV', 'field_type':'text', 'display_order':34},
#    {'id': 35, 'name': 'Project Cluster EV', 'field_type':'text', 'display_order':35},
#    {'id': 36, 'name': 'Preferred Charge Client', 'field_type':'text', 'display_order':36},
#    {'id': 37, 'name': 'Lease Partner EV', 'field_type':'text', 'display_order':37},
#    {'id': 38, 'name': 'Status PV',  'field_type':'dropdown', 'options':['0 - Early-Stage', '1 - Lead', '2 - Pitch', '3 - Negotiations', '4 - LOI Signed/Development', '5 - Construction Ready', '6 - Construction', '7 - Installed', '	8 - Operating', '	9 - Discontinued', 'H - On Hold'], 'display_order':38},
#    {'id': 39, 'name': 'Project Cluster PV', 'field_type':'text', 'display_order':39},
#    {'id': 40, 'name': 'COS PV', 'field_type':'dropdown', 'options':['approved', 'applied'], 'display_order':40},
#    {'id': 41, 'name': 'Asset Management Comments PV', 'field_type':'longtext', 'display_order':41},
#    {'id': 42, 'name': 'Pitch PV', 'field_type':'text', 'display_order':42},
#    {'id': 43, 'name': 'LOI PV', 'field_type':'text', 'display_order':43},
#    {'id': 44, 'name': 'Setup PV', 'field_type':'text', 'display_order':44},
#    {'id': 45, 'name': 'Construction PV', 'field_type':'text', 'display_order':45},
#    {'id': 46, 'name': 'Installed PV', 'field_type':'text', 'display_order':46},
#    {'id': 47, 'name': 'Operating PV', 'field_type':'text', 'display_order':47},
#    {'id': 48, 'name': 'Invoice Number PV', 'field_type':'text', 'display_order':48},
#    {'id': 49, 'name': 'Approval PV', 'field_type':'text', 'display_order':49},
#    {'id': 50, 'name': 'Milestone Date PV', 'field_type':'date', 'display_order':50},
#    {'id': 51, 'name': 'Disc Reason PV', 'field_type':'text', 'display_order':51},
#    {'id': 52, 'name': 'Lease Partner PV', 'field_type':'text', 'display_order':52},
#    {'id': 53, 'name': 'Exp kWp', 'field_type':'decimal', 'display_order':53},
#    {'id': 54, 'name': 'Exp Spec Yield PV', 'field_type':'text', 'display_order':54},
#    {'id': 55, 'name': 'Construction Year PV', 'field_type':'integer', 'display_order':55},
#    {'id': 56, 'name': 'Construction Quarter PV', 'field_type':'text', 'display_order':56},
#    {'id': 57, 'name': 'Exp Installation Date PV', 'field_type':'date', 'display_order':57},
#    {'id': 58, 'name': 'Planned Installtion Date PV', 'field_type':'date', 'display_order':58},
#    {'id': 59, 'name': 'Exp Operation Date PV', 'field_type':'date', 'display_order':59},
#    {'id': 60, 'name': 'Capex Spent To Date PV', 'field_type':'date', 'display_order':60},
#    {'id': 61, 'name': 'Capex Total Expected PV', 'field_type':'decimal', 'display_order':61},
#    {'id': 62, 'name': 'Offtakers PV', 'field_type':'decimal', 'display_order':62},
#    {'id': 63, 'name': 'Name', 'field_type':'text', 'display_order':1},

   
# ]

def create_fields():
   for field_data in fields:
       field_id = field_data['id']
       if not Field.objects.filter(id=field_id).exists():
           Field.objects.create(**field_data)