# Generated by Django 4.2.1 on 2024-07-31 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0002_initial'),
        ('locations', '0001_initial'),
        ('projectmanagement', '0001_initial'),
        ('partners', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsubtenant',
            name='subtenant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='locationrole',
            name='locations_id',
            field=models.ManyToManyField(to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationrole',
            name='partners_id',
            field=models.ManyToManyField(to='partners.partner'),
        ),
        migrations.AddField(
            model_name='locationrole',
            name='roles_id',
            field=models.ManyToManyField(to='locations.role'),
        ),
        migrations.AddField(
            model_name='locationpartnertype',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationpartnertype',
            name='partner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner'),
        ),
        migrations.AddField(
            model_name='locationpartnertype',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.type'),
        ),
        migrations.AddField(
            model_name='locationmeasuresettings',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationmeasures',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationmalovalues',
            name='location_malo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationmalos'),
        ),
        migrations.AddField(
            model_name='locationmalos',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationdeviceslot',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationdevicemalos',
            name='location_malos_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationmalos'),
        ),
        migrations.AddField(
            model_name='locationcontract',
            name='contract_id',
            field=models.ManyToManyField(to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='locationcontract',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.countries'),
        ),
        migrations.AddField(
            model_name='location',
            name='current_phase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectmanagement.projectphase'),
        ),
        migrations.AddField(
            model_name='location',
            name='land_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_location', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='location',
            name='lead_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_company', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='location',
            name='lead_manager_ev',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EV_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='lead_manager_pv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PV_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='property_manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_location', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_ev_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_ev', to='locations.locationstatusevpv'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.status'),
        ),
        migrations.AddField(
            model_name='location',
            name='status_pv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_pv', to='locations.locationstatusevpv'),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leased_location', to='partners.partner'),
        ),
    ]
