# Generated by Django 4.2.1 on 2024-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(blank=True, max_length=955, null=True)),
                ('subject', models.CharField(max_length=955)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.IntegerField(null=True)),
                ('body', models.CharField(max_length=955)),
                ('is_seen', models.BooleanField(default=False)),
                ('data_id', models.IntegerField()),
                ('data_name', models.CharField(max_length=955)),
                ('assigned_by_id', models.IntegerField()),
                ('assigned_by_name', models.CharField(max_length=955)),
                ('location_name', models.CharField(blank=True, max_length=955, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
